# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Projects/Posts"
email: gffuentes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you will find a portfolio of sorts - my goal is to add different projects   and brief lessons I learned from them. I will also occassionaly post things
  that I feel others may be able to learn from. Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gffuentes.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gffuentes
linkedin_username: gabeffuentes

# Build settings
markdown: kramdown
